#!/bin/bash
# Builds "HSA Tracker.app" — a double-clickable macOS launcher that starts the
# server (if it isn't already running) and opens the dashboard in your browser.
# Usage:  npm run make-launcher        (puts the app on your Desktop)
#         scripts/make-launcher.sh /some/other/destination
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${1:-$HOME/Desktop}"
BUNDLE="$DEST/HSA Tracker.app"
PORT=8321

echo "Building launcher for: $APP_DIR"
rm -rf "$BUNDLE"
mkdir -p "$BUNDLE/Contents/MacOS" "$BUNDLE/Contents/Resources"

# ---------- Info.plist ----------
cat > "$BUNDLE/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>HSA Tracker</string>
  <key>CFBundleDisplayName</key><string>HSA Tracker</string>
  <key>CFBundleIdentifier</key><string>local.hsa-tracker.launcher</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST

# ---------- Launcher executable ----------
cat > "$BUNDLE/Contents/MacOS/launcher" <<LAUNCH
#!/bin/bash
# Auto-generated by make-launcher.sh — regenerate rather than editing.
# Opens HSA Tracker as a one-piece desktop app (Electron). If it's already
# open, the running window is focused instead (single-instance lock).
APP_DIR="$APP_DIR"
export PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"

NODE="\$(command -v node || true)"
if [ -z "\$NODE" ]; then
  osascript -e 'display alert "HSA Tracker" message "Node.js was not found. Install it free from nodejs.org, then try again."'
  exit 1
fi

cd "\$APP_DIR"
mkdir -p data
if [ ! -x node_modules/.bin/electron ]; then
  osascript -e 'display notification "One-time install of components — this can take a few minutes. The app will open when ready." with title "HSA Tracker"'
  npm install >> data/server.log 2>&1 || {
    osascript -e 'display alert "HSA Tracker" message "Installing components failed. Check hsa-tracker/data/server.log for details."'
    exit 1
  }
fi

nohup node_modules/.bin/electron . >> data/server.log 2>&1 &
LAUNCH
chmod +x "$BUNDLE/Contents/MacOS/launcher"

# ---------- Icon (rendered from SVG with stock macOS tools; skipped if anything fails) ----------
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cat > "$TMP/icon.svg" <<'SVG'
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#3987e5"/>
      <stop offset="1" stop-color="#1c5cab"/>
    </linearGradient>
  </defs>
  <rect x="60" y="60" width="904" height="904" rx="200" fill="url(#g)"/>
  <g fill="#ffffff">
    <rect x="330" y="270" width="86" height="484" rx="43"/>
    <rect x="608" y="270" width="86" height="484" rx="43"/>
    <rect x="330" y="469" width="364" height="86" rx="43"/>
    <circle cx="760" cy="750" r="150" fill="#0ca30c" stroke="#ffffff" stroke-width="44"/>
    <path d="M690 750 l50 50 l95 -95" fill="none" stroke="#ffffff" stroke-width="40" stroke-linecap="round" stroke-linejoin="round"/>
  </g>
</svg>
SVG
if qlmanage -t -s 1024 -o "$TMP" "$TMP/icon.svg" >/dev/null 2>&1 && [ -f "$TMP/icon.svg.png" ]; then
  ICONSET="$TMP/AppIcon.iconset"
  mkdir -p "$ICONSET"
  for size in 16 32 128 256 512; do
    sips -z $size $size "$TMP/icon.svg.png" --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
    dbl=$((size * 2))
    sips -z $dbl $dbl "$TMP/icon.svg.png" --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$BUNDLE/Contents/Resources/AppIcon.icns" 2>/dev/null \
    && echo "Icon built." || echo "Icon conversion failed — the app will use a generic icon."
else
  echo "Could not render the icon (qlmanage unavailable) — the app will use a generic icon."
fi

echo "Done: $BUNDLE"
echo "Double-click it to open HSA Tracker. Drag it to the Dock to pin it."
